@endpoint = http://localhost:4000
### check up
GET {{endpoint}}


### Get products
GET {{endpoint}}/api/v1/products

### Register
POST {{endpoint}}/api/v1/auth/register
Content-Type: application/json

{
  "username": "Vipzfern",
  "email": "fern2541@hotmail.com",
  "password" : "Qwe",
  "store_name" : "Retita.cutetape",
  "store_type" : 1
}


### Login
POST {{endpoint}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "m9nood",
  "password" : "7848055df09311652b2ac208549e981c9c529f88"
}