@endpoint = http://localhost:4000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Im05bm9vZCIsImVtYWlsIjoic3B3Lm50d0BnbWFpbC5jb20iLCJzdG9yZV9pZCI6MSwiZXhwIjoxNjM3MzA0MjQxLCJpYXQiOjE2MzcyMTc4NDEsImlzcyI6Im05In0.DFqr3TUDLmVIP807BpO3JWTd47WkBvPWb7YeRLE6VOw
### check up
GET {{endpoint}}


### Get products
GET {{endpoint}}/api/v1/products?page=2&pageSize=1
Content-Type: application/json
Authorization: Bearer {{token}}

### Register
POST {{endpoint}}/api/v1/auth/register
Content-Type: application/json

{
  "username": "Vipzfern",
  "email": "fern2541@hotmail.com",
  "password" : "Qwe",
  "store_name" : "Retita.cutetape",
  "store_type" : 1
}


### Login
POST {{endpoint}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "m9nood",
  "password" : "7848055df09311652b2ac208549e981c9c529f88"
}